apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamodb-pvc
  namespace: url-shortener
  labels:
    app: dynamodb-local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
