apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: url-shortener
  labels:
    app: kafka
spec:
  clusterIP: None
  ports:
    - port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka
